"""empty message

Revision ID: 343f5c477a78
Revises: 49acd329d0f0
Create Date: 2018-10-25 15:31:03.632585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '343f5c477a78'
down_revision = '49acd329d0f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'name',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=120),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###
