"""empty message

Revision ID: 49acd329d0f0
Revises: 619a5af6b011
Create Date: 2018-10-25 12:18:56.514636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49acd329d0f0'
down_revision = '619a5af6b011'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'events', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'user_id')
    # ### end Alembic commands ###
