"""empty message

Revision ID: d66ae3c20338
Revises: 343f5c477a78
Create Date: 2018-10-25 16:07:24.818032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd66ae3c20338'
down_revision = '343f5c477a78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('events_image_key', 'events', type_='unique')
    op.drop_constraint('events_location_key', 'events', type_='unique')
    op.drop_constraint('events_name_key', 'events', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('events_name_key', 'events', ['name'])
    op.create_unique_constraint('events_location_key', 'events', ['location'])
    op.create_unique_constraint('events_image_key', 'events', ['image'])
    # ### end Alembic commands ###
